name: go test
on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  test:
    services:
      runs-on: ubuntu-latest
      mysql:
        image: mysql:8
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 20s
          --health-timeout 10s
          --health-retries 10
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: go_posts
          MYSQL_USER: app
          MYSQL_PASSWORD: app
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.18"
      - uses: actions/checkout@v3
      - run: |
          go install github.com/k0kubun/sqldef/cmd/mysqldef@latest
          mysqldef -u app -p app -h 127.0.0.1 -P 3306 go_posts < ./mysql/schema.sql
      - run: go test ./... -coverprofile=coverage.out
      - name: report coverage
        uses: k1LoW/octocov-action@v0
