version: "3.9"

volumes:
  go_posts_db_data:


services:
  app:
    image: gotodo
    build:
      args:
        - target=dev
    environment:
      APP_ENV: dev
      PORT: 8080
      DB_HOST: localhost
      DB_PORT: 33306
      DB_USER: app
      DB_PASSWORD: app
      DB_NAME: go_posts
    volumes:
      - .:/app
    ports:
      - "18000:8080"
  go_posts_db:
    image: mysql
    platform: linux/amd64
    container_name: go_posts_db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_DATABASE: go_posts
    volumes:
      - go_posts_db_data:/var/lib/mysql
      - $PWD/mysql/conf.d:/etc/mysql/conf.d:cached
    ports:
      - "33306:3306"
