version: "3.9"

volumes:
  go-posts-db:

services:
  app:
    build:
      args:
        - target=dev
    environment:
      APP_ENV: dev
      PORT: 8080
      DB_HOST: go-posts-db
      DB_PORT: 3306
      DB_USER: posts
      DB_PASSWORD: posts
      DB_NAME: posts
      # REDIS_HOST: go-posts-redis
      # REDIS_PORT: 6379
    volumes:
      - .:/app
    ports:
      - "18000:8080"
  go-posts-db:
    image: mysql:8.0
    container_name: go-posts-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: posts
      MYSQL_PASSWORD: posts
      MYSQL_DATABASE: posts
    volumes:
      - go-posts-db:/var/lib/mysql
      - $PWD/mysql/conf.d:/etc/mysql/conf.d:cached
    ports:
      - "33306:3306"
